using CommonLibExtended.Helpers;
using CommonLibExtended.Traders.Models;
using CommonLibExtended.Traders.Services;
using SPTarkov.DI.Annotations;
using SPTarkov.Server.Core.Models.Common;
using SPTarkov.Server.Core.Models.Eft.Common.Tables;
using SPTarkov.Server.Core.Models.Spt.Config;
using SPTarkov.Server.Core.Servers;
using SPTarkov.Server.Core.Services;
using System.Globalization;

namespace CommonLibExtended.Traders.TraderHelpers;

[Injectable]
public sealed class CustomTraderSettingsHelper(
    TraderPricingService pricingService,
    DatabaseService databaseService,
    DebugLogHelper logger,
    ConfigServer configServer)
{
    private const double DefaultBarterValueTolerance = 0.15;
    private const int DefaultMaxBarterComponents = 3;

    private readonly TraderPricingService _pricing = pricingService;
    private readonly DebugLogHelper _log = logger;
    private readonly DatabaseService _databaseService = databaseService;
    private readonly ConfigServer _configServer = configServer;

    public void ApplyPricing(TraderAssort assort, CustomTraderSettings settings)
    {
        if (assort?.Items == null || assort.BarterScheme == null || assort.LoyalLevelItems == null)
        {
            return;
        }

        var manualOverridesApplied = 0;
        var generatedOverridesApplied = 0;
        var skippedOffers = 0;
        var skippedBecauseNotConfigured = 0;
        var skippedBecauseNoPrice = 0;
        var skippedBecauseBuildFailed = 0;

        foreach (var item in assort.Items)
        {
            if (item?.ParentId != "hideout")
            {
                continue;
            }

            if (!assort.BarterScheme.TryGetValue(item.Id, out var schemeLists) || schemeLists == null || schemeLists.Count == 0)
            {
                skippedOffers++;
                continue;
            }

            if (!assort.LoyalLevelItems.ContainsKey(item.Id))
            {
                skippedOffers++;
                continue;
            }

            if (settings.AssortBarterOverrides == null ||
                !settings.AssortBarterOverrides.TryGetValue(item.Id, out var assortOverride) ||
                assortOverride == null ||
                !assortOverride.Enabled)
            {
                skippedOffers++;
                skippedBecauseNotConfigured++;
                continue;
            }

            var targetPrice = settings.UseAttachmentPricing
                ? _pricing.GetWeaponBuildPrice(item.Id, assort, settings)
                : _pricing.GetItemPrice(item.Template, settings, assortOverride.PriceSource);

            _log.LogService(
                nameof(CustomTraderSettingsHelper),
                $"Calculated target price for assortId={item.Id}, tpl={item.Template}, priceSource={assortOverride.PriceSource ?? "default"}: {targetPrice}",
                nameof(ApplyPricing));

            if (targetPrice <= 0)
            {
                targetPrice = _pricing.GetFallbackCategoryRarityPrice(item.Template, settings);

                _log.LogService(
                    nameof(CustomTraderSettingsHelper),
                    $"Fallback target price for assortId={item.Id}, tpl={item.Template}: {targetPrice}",
                    nameof(ApplyPricing));

                if (targetPrice <= 0)
                {
                    skippedOffers++;
                    skippedBecauseNoPrice++;
                    continue;
                }
            }

            targetPrice = Math.Round(targetPrice * settings.PriceMultiplier);

            if (!assortOverride.UseAutoGeneratedBarter)
            {
                var manualScheme = CloneScheme(assortOverride.ManualScheme);

                if (manualScheme.Count == 0)
                {
                    skippedOffers++;
                    skippedBecauseBuildFailed++;

                    _log.LogError(
                        nameof(CustomTraderSettingsHelper),
                        $"Manual barter override for assortId={item.Id} was enabled but ManualScheme was empty or invalid",
                        nameof(ApplyPricing));

                    continue;
                }

                assort.BarterScheme[item.Id] = [manualScheme];
                manualOverridesApplied++;

                _log.LogService(
                    nameof(CustomTraderSettingsHelper),
                    $"Applied manual barter override for assortId={item.Id} with {manualScheme.Count} component(s)",
                    nameof(ApplyPricing));

                continue;
            }

            var generatedScheme = TryBuildBarterSchemeFromTargetPrice(targetPrice, settings, assortOverride);

            if (generatedScheme == null || generatedScheme.Count == 0)
            {
                skippedOffers++;
                skippedBecauseBuildFailed++;

                _log.LogError(
                    nameof(CustomTraderSettingsHelper),
                    $"Failed to auto-generate barter override for assortId={item.Id}, tpl={item.Template}, targetPrice={targetPrice}",
                    nameof(ApplyPricing));

                continue;
            }

            assort.BarterScheme[item.Id] = [generatedScheme];
            generatedOverridesApplied++;

            _log.LogService(
                nameof(CustomTraderSettingsHelper),
                $"Applied generated barter override for assortId={item.Id} with {generatedScheme.Count} component(s), targetPrice={targetPrice}",
                nameof(ApplyPricing));
        }

        _log.LogService(
            nameof(CustomTraderSettingsHelper),
            $"ApplyPricing → manualOverridesApplied={manualOverridesApplied}, generatedOverridesApplied={generatedOverridesApplied}, skippedOffers={skippedOffers}, skippedBecauseNotConfigured={skippedBecauseNotConfigured}, skippedBecauseNoPrice={skippedBecauseNoPrice}, skippedBecauseBuildFailed={skippedBecauseBuildFailed}",
            nameof(ApplyPricing));
    }

    private List<BarterScheme>? TryBuildBarterSchemeFromTargetPrice(
        double targetPrice,
        CustomTraderSettings settings,
        AssortBarterOverride assortOverride)
    {
        if (targetPrice <= 0)
        {
            return null;
        }

        var preferredTpls = assortOverride.PreferredBarterTpls?
            .Where(tpl => !string.IsNullOrWhiteSpace(tpl))
            .Distinct(StringComparer.OrdinalIgnoreCase)
            .ToList();

        if (preferredTpls == null || preferredTpls.Count == 0)
        {
            _log.LogError(
                nameof(CustomTraderSettingsHelper),
                "Auto-generated barter override requires PreferredBarterTpls but none were configured",
                nameof(TryBuildBarterSchemeFromTargetPrice));

            return null;
        }

        var tolerance = Math.Max(
            1,
            targetPrice * (assortOverride.BarterValueTolerance > 0
                ? assortOverride.BarterValueTolerance
                : DefaultBarterValueTolerance));

        var maxComponents = Math.Max(
            1,
            assortOverride.MaxBarterComponents > 0
                ? assortOverride.MaxBarterComponents
                : DefaultMaxBarterComponents);

        var pool = preferredTpls
            .Select(tpl => new
            {
                Tpl = tpl,
                Price = _pricing.GetItemPrice(tpl, settings, assortOverride.PriceSource)
            })
            .Where(x => x.Price > 0)
            .OrderByDescending(x => x.Price)
            .ToList();

        if (pool.Count == 0)
        {
            _log.LogError(
                nameof(CustomTraderSettingsHelper),
                "Auto-generated barter override pool had no valid priced items",
                nameof(TryBuildBarterSchemeFromTargetPrice));

            return null;
        }

        var scheme = new List<BarterScheme>();
        var remaining = targetPrice;

        foreach (var poolItem in pool)
        {
            if (scheme.Count >= maxComponents || remaining <= tolerance)
            {
                break;
            }

            var count = (int)Math.Floor(remaining / poolItem.Price);
            if (count <= 0)
            {
                continue;
            }

            count = Math.Min(count, 99);

            scheme.Add(new BarterScheme
            {
                Template = poolItem.Tpl,
                Count = count
            });

            remaining -= poolItem.Price * count;
        }

        if (remaining > tolerance)
        {
            var nearest = pool
                .OrderBy(x => Math.Abs(x.Price - remaining))
                .FirstOrDefault();

            if (nearest != null)
            {
                var existing = scheme.FirstOrDefault(x =>
                    string.Equals(x.Template, nearest.Tpl, StringComparison.OrdinalIgnoreCase));

                if (existing != null)
                {
                    existing.Count = (existing.Count ?? 0) + 1;
                }
                else if (scheme.Count < maxComponents)
                {
                    scheme.Add(new BarterScheme
                    {
                        Template = nearest.Tpl,
                        Count = 1
                    });
                }
            }
        }

        if (scheme.Count == 0)
        {
            return null;
        }

        var totalValue = scheme.Sum(x =>
        {
            if (x?.Template == null || x.Count.HasValue != true)
            {
                return 0;
            }

            return _pricing.GetItemPrice(x.Template, settings, assortOverride.PriceSource) * x.Count.Value;
        });

        if (Math.Abs(totalValue - targetPrice) > tolerance)
        {
            _log.LogError(
                nameof(CustomTraderSettingsHelper),
                $"Generated barter scheme rejected because totalValue={totalValue} was outside tolerance={tolerance} for targetPrice={targetPrice}",
                nameof(TryBuildBarterSchemeFromTargetPrice));

            return null;
        }

        return scheme;
    }

    private static List<BarterScheme> CloneScheme(IEnumerable<BarterScheme>? source)
    {
        if (source == null)
        {
            return [];
        }

        return source
            .Where(x =>
                x != null &&
                !string.IsNullOrWhiteSpace(x.Template) &&
                x.Count.HasValue &&
                x.Count.Value > 0)
            .Select(x => new BarterScheme
            {
                Template = x.Template,
                Count = x.Count
            })
            .ToList();
    }

    public void ApplyAssortSettings(TraderAssort assort, CustomTraderSettings settings)
    {
        if (assort?.Items == null)
        {
            return;
        }

        var random = new Random();
        var toRemove = new List<string>();

        foreach (var item in assort.Items)
        {
            if (item?.ParentId != "hideout" || item.Upd == null)
            {
                continue;
            }

            if (settings.RandomizeStockAvailable &&
                random.Next(0, 100) < settings.OutOfStockChance)
            {
                toRemove.Add(item.Id);
                continue;
            }

            if (settings.UnlimitedStock)
            {
                item.Upd.UnlimitedCount = true;
                item.Upd.StackObjectsCount = 999999;
            }
            else
            {
                item.Upd.UnlimitedCount = false;

                if (item.Upd.StackObjectsCount <= 0)
                {
                    item.Upd.StackObjectsCount = 100;
                }
            }
        }

        var initialRootCount = assort.Items.Count(x => x.ParentId == "hideout");
        var removedRootCount = toRemove.Count;

        if (removedRootCount > 0)
        {
            assort.Items.RemoveAll(x => toRemove.Contains(x.Id) || toRemove.Contains(x.ParentId));

            foreach (var id in toRemove)
            {
                assort.BarterScheme.Remove(id);
                assort.LoyalLevelItems.Remove(id);
            }
        }

        var percent = initialRootCount > 0
            ? removedRootCount / (double)initialRootCount * 100
            : 0;

        _log.LogService(
            nameof(CustomTraderSettingsHelper),
            $"Assort cleanup: {removedRootCount}/{initialRootCount} removed ({percent:F1}%)",
            nameof(ApplyAssortSettings));
    }

    public void ApplyBaseSettings(TraderBase traderBase, CustomTraderSettings settings)
    {
        if (traderBase == null)
        {
            return;
        }

        settings.Validate(traderBase.Id);

        traderBase.UnlockedByDefault = settings.UnlockedByDefault;

        if (traderBase.LoyaltyLevels?.Count > 0)
        {
            traderBase.LoyaltyLevels[0].MinLevel = settings.MinLevel;

            foreach (var level in traderBase.LoyaltyLevels)
            {
                TrySetInsuranceCoefficient(level, settings.InsurancePriceCoef, traderBase.Id);
            }
        }

        if (traderBase.Repair != null)
        {
            traderBase.Repair.Quality = settings.RepairQuality;
        }

        _log.LogService(
            nameof(CustomTraderSettingsHelper),
            $"BaseSettings applied → Trader={traderBase.Id}, MinLevel={settings.MinLevel}, RepairQ={settings.RepairQuality}, InsuranceCoef={settings.InsurancePriceCoef}",
            nameof(ApplyBaseSettings));
    }

    private void TrySetInsuranceCoefficient(object loyaltyLevel, double insurancePriceCoef, string traderId)
    {
        if (loyaltyLevel == null)
        {
            return;
        }

        try
        {
            var prop = loyaltyLevel.GetType().GetProperty("InsurancePriceCoefficient");

            if (prop == null || !prop.CanWrite)
            {
                return;
            }

            var targetType = Nullable.GetUnderlyingType(prop.PropertyType) ?? prop.PropertyType;
            var value = Convert.ChangeType(insurancePriceCoef, targetType, CultureInfo.InvariantCulture);

            prop.SetValue(loyaltyLevel, value);
        }
        catch (Exception ex)
        {
            _log.LogError(
                nameof(CustomTraderSettingsHelper),
                $"Insurance coef failed for trader {traderId}: {ex.Message}",
                nameof(TrySetInsuranceCoefficient));
        }
    }

    public void ApplyFleaSettings(TraderBase traderBase, CustomTraderSettings settings)
    {
        var ragfairConfig = _configServer.GetConfig<RagfairConfig>();

        if (ragfairConfig == null || traderBase == null)
        {
            return;
        }

        if (settings.AddTraderToFleaMarket)
        {
            ragfairConfig.Traders[traderBase.Id] = true;
        }
        else
        {
            ragfairConfig.Traders.Remove(traderBase.Id);
        }

        _log.LogService(
            nameof(CustomTraderSettingsHelper),
            $"FleaSettings → Trader={traderBase.Id}, Enabled={settings.AddTraderToFleaMarket}",
            nameof(ApplyFleaSettings));
    }

    public int ApplyRefreshSettings(TraderBase traderBase, CustomTraderSettings settings)
    {
        var traderConfig = _configServer.GetConfig<TraderConfig>();

        if (traderConfig == null || traderBase == null)
        {
            return 0;
        }

        var random = new Random();
        var refreshTime = random.Next(settings.TraderRefreshMin, settings.TraderRefreshMax + 1);

        traderConfig.UpdateTime.RemoveAll(x => x.TraderId == traderBase.Id);

        traderConfig.UpdateTime.Add(new UpdateTime
        {
            TraderId = traderBase.Id,
            Seconds = new MinMax<int>(refreshTime, refreshTime)
        });

        traderBase.NextResupply = (int)(DateTimeOffset.UtcNow.ToUnixTimeSeconds() + refreshTime);

        _log.LogService(
            nameof(CustomTraderSettingsHelper),
            $"RefreshSettings → Trader={traderBase.Id}, Refresh={refreshTime}s",
            nameof(ApplyRefreshSettings));

        return refreshTime;
    }
}